config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'recipes#index'

  resources :recipes do 
    post 'send_message'
  end
  resources :recipe_types, only: %i[show new create]
  resources :cuisines, only: %i[show new create]
  resources :lists, only: %i[index show]
  get 'search', to: 'recipes#search'
  get '/profile', to: 'users#profile'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cuisine.rb
class Cuisine < ApplicationRecord
  validates :name, presence: { message: "Preencher todos os campos" }
  validates :name, uniqueness: { message: "Ja existe cozinha com este nome" }
  has_many :recipes
end

app/models/list.rb
class List < ApplicationRecord
  belongs_to :user
  has_many :list_recipes
  has_many :recipes, through: :list_recipes
end

app/models/list_recipe.rb
class ListRecipe < ApplicationRecord
  belongs_to :recipe
  belongs_to :list
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :cuisine
  belongs_to :recipe_type
  belongs_to :user
  has_many :list_recipes
  has_many :lists, through: :list_recipes
  has_one_attached :photo

  validates :title, :difficulty, :cook_time, :cook_method,
            :ingredients, presence: true

  def cook_time_min
    "#{cook_time} minutos"
  end

  def self.search_by_title(title)
    where(title: title)
  end
end

app/models/recipe_type.rb
class RecipeType < ApplicationRecord
  has_many :recipes

  validates :name, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :recipes
  has_many :lists
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cuisines_controller.rb
class CuisinesController < ApplicationController
  
  def new
    @cuisine = Cuisine.new
  end

  def create
    @cuisine = Cuisine.new(cuisine_params)
    flash[:alert] = 'Cozinha cadastrada com sucesso'
    return redirect_to @cuisine if @cuisine.save
    
    render :new
  end

  def show
    @cuisine = Cuisine.find(params[:id])
  end

  private 
  
  def cuisine_params
    params.require(:cuisine).permit(:name)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  
  def index
    @lists = current_user.lists
  end

  def show
    @list = List.find(params[:id])
  end
end

app/controllers/recipe_types_controller.rb
class RecipeTypesController < ApplicationController
  def show
    @recipe_type = RecipeType.find(params[:id])
  end

  def new
    @recipe_type = RecipeType.new
  end

  def create
    @recipe_type = RecipeType.new(recipe_type_params)
    return redirect_to @recipe_type if @recipe_type.save

    render :new
  end

  private

  def recipe_type_params
    params.require(:recipe_type).permit(:name)
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: %i[show edit update]
  before_action :authenticate_user!, only: [:new, :create]
  def index
    @recipes = Recipe.all
  end

  def show; end

  def new
    @recipe = Recipe.new
    @recipe_types = RecipeType.all
    @cuisines = Cuisine.all
  end

  def create
    @recipe = Recipe.new(recipe_params)
    @recipe.user = current_user
    return redirect_to @recipe if @recipe.save

    @recipe_types = RecipeType.all
    @cuisines = Cuisine.all
    render :new
  end

  def edit
    @recipe_types = RecipeType.all
    @cuisines = Cuisine.all
  end

  def update
    return redirect_to @recipe if @recipe.update(recipe_params)

    @recipe_types = RecipeType.all
    @cuisines = Cuisine.all
    render :edit
  end

  def destroy
    @recipe = Recipe.find(params[:id])
    @recipe.destroy
    redirect_to root_path
  end

  def search
    @recipes = Recipe.where("title LIKE ? ", "%#{params[:search]}%")
  end

  def send_message
    RecipesMailer.send_recipe(params[:recipe_id].to_i,
                               params[:from],
                               params[:to],
                               params[:message])
    flash[:notice] = 'E-mail enviado com sucesso!'
    redirect_to recipe_path(params[:recipe_id])
  end

  private

  def set_recipe
    @recipe = Recipe.find(params[:id])
  end

  def recipe_params
    params.require(:recipe).permit(:title, :recipe_type_id, :cuisine_id,
                                   :difficulty, :cook_time, :ingredients,
                                   :cook_method, :photo)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def profile; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/cuisines/_form.html.erb
<%= form_with model: cuisine do |c| %>
  <%= c.label :name, 'Nome' %>
  <%= c.input :name, 'Nome' %>
  
  <%= f.submit 'Salvar', class: 'btn btn-primary' %>

<% end %>

app/views/cuisines/new.html.erb
<h1>Nova Cozinha</h1>
<% @cuisine.errors.full_messages.each do |error| %>
 
    <%= error %>
 
<% end %>

<%= form_with model: @cuisine, local: true do |c| %>
  
  <%= c.label :name, 'Nome' %>
  <%= c.text_field :name %>
  <%= c.submit 'Salvar', class: 'btn btn-primary' %>
<% end %>

app/views/cuisines/show.html.erb
<h1>Cozinha</h1>
<%= alert %>
<h1><%= @cuisine.name %></h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cookbook</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <div class="container mt-4">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= yield %>
    </div>
  </body>
</html>

app/views/lists/index.html.erb
<ul>
<% @lists.each do |list|%>
  <li>
    <%= link_to list.name, list_path(list.id) %>
  </li>
<% end %>  
</ul>

app/views/lists/show.html.erb
<h1>
  <%= @list.name %>
</h1>
  <% @list.recipes.each do |recipe| %>
    <%= render recipe %>
  <% end %>

app/views/recipe_types/_form.html.erb
<div>
  <% if @recipe_type.errors.any? %>
    <p>Você deve informar o nome do tipo de receita</p>
  <% end %>
</div>

<%= form_with model: @recipe_type do |f| %>
  <div class="form-group">
    <%= f.label :name, 'Nome' %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>
  <%= f.submit 'Enviar', class: 'btn btn-primary' %>
<% end %>

app/views/recipe_types/new.html.erb
<%= render 'form', locals: { recipe_type: @recipe_type } %>

app/views/recipe_types/show.html.erb
<h1><%= @recipe_type.name %></h1>

<%= render partial: 'recipes/recipe', collection: @recipe_type.recipes %>

app/views/recipes/_form.html.erb
<div>
  <% if recipe.errors.any? %>
    <p>Não foi possível salvar a receita</p>
  <% end %>
</div>

<%= form_with model: recipe do |f| %>
  <div class="form-group">
    <%= f.label :title, 'Título' %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :recipe_type_id, 'Tipo da Receita' %>
    <%= f.collection_select :recipe_type_id, recipe_types, :id, :name, {}, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :cuisine_id, 'Cozinha' %>
    <%= f.collection_select :cuisine_id, cuisines, :id, :name, {}, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :difficulty, 'Dificuldade' %>
    <%= f.text_field :difficulty, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :cook_time, 'Tempo de Preparo' %>
    <%= f.text_field :cook_time, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :ingredients, 'Ingredientes' %>
    <%= f.text_area :ingredients, class: 'form-control', row: '3' %>
  </div>
  <div class="form-group">
    <%= f.label :cook_method, 'Como Preparar' %>
    <%= f.text_area :cook_method, class: 'form-control', row: '3' %>
  </div>

  <div class="form-group">
    <%= f.label :photo, 'Foto' %>
    <%= f.file_field :photo %>
  </div>

    
  <%= f.submit 'Enviar', class: 'btn btn-primary' %>
<% end %>

app/views/recipes/_recipe.html.erb
<h1><%= link_to recipe.title, recipe %></h1>
<ul>
  <li><%= recipe.recipe_type.name %></li>
  <li><%= recipe.cuisine.name %></li>
  <li><%= recipe.difficulty %></li>
  <li><%= recipe.cook_time_min %></li>
</ul>

app/views/recipes/edit.html.erb
<h1>Editar receita</h1>

<%= render partial: 'form', locals: { recipe: @recipe, recipe_types: @recipe_types, cuisines: @cuisines } %>

app/views/recipes/index.html.erb
<h1>CookBook</h1>
<p>Bem-vindo ao maior livro de receitas online</p>

<%= render @recipes %>

<%= pluralize(@recipes.count, 'Receita encontrada', plural: 'Receitas encontradas') %>

app/views/recipes/new.html.erb
<h1>Nova receita</h1>

<%= render partial: 'form', locals: { recipe: @recipe, recipe_types: @recipe_types, cuisines: @cuisines } %>

app/views/recipes/search.html.erb
<% if @recipes.empty? %>
  <h3>Nenhum resultado foi encontrado</h3>
<% end %>
<%= render @recipes %>

app/views/recipes/show.html.erb
<h1><%= @recipe.title %></h1>
<%= image_tag @recipe.photo if @recipe.photo.attached? %>

<h3>Detalhes</h3>

<p><strong>Tipo da receita</strong></p>
<p><%= @recipe.recipe_type.name %></p>
<p><strong>Cozinha</strong></p>
<p><%= @recipe.cuisine.name %></p>
<p><strong>Dificuldade</strong></p>
<p><%= @recipe.difficulty %></p>
<p><strong>Tempo de preparo</strong></p>
<p><%= @recipe.cook_time_min %></p>

<h3>Ingredientes</h3>
<p><%= @recipe.ingredients %></p>

<h3>Como Preparar</h3>
<p><%= @recipe.cook_method %></p>

<h3>Enviar para um amigo</h3>
<%= form_tag(recipe_send_message_path(@recipe)) do %>
  <div>
    <%= label_tag :from, 'De:' %>
    <%= text_field_tag :from %>
  </div>
  <div>
    <%= label_tag :to, 'Para:' %>
    <%= text_field_tag :to %>
  </div>
  <div>
    <%= label_tag :message, 'Mensagem:' %>
    <%= text_area_tag :message %>
  </div>
  <div>
    <%= submit_tag 'Enviar' %>
  </div>
<% end %>

<% if user_signed_in? && @recipe.user == current_user %>
  <%= link_to 'Editar', edit_recipe_path(@recipe), class: 'btn btn-info' %>
  <%= link_to 'Excluir', recipe_path(@recipe), method: :delete, class: 'btn btn-info' %>
  <% end %>
<%= link_to 'Voltar', root_path, class: 'btn btn-secondary' %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="<%= root_path %>">CookBook</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="<%= root_path %>">Home <span class="sr-only">(current)</span></a>
        </li>
      <% if user_signed_in? %>
        <li class="nav-item">
          <a class="nav-link" href="<%= new_recipe_path %>">Enviar uma receita</a>
        </li>
      <% end %>
      <li class="nav-item">
        <%= link_to 'Cadastrar tipo de receita', new_recipe_type_path, class: 'nav-link' %>
      </li>
       <li class="nav-item">
        <%= link_to 'Cadastrar cozinha', new_cuisine_path, class: 'nav-link' %>
      </li>
      <li>
        <%= form_tag(search_path, method: :get) do %>
          <%= label_tag 'search', 'Nome da Receita' %>
          <%= text_field_tag 'search', '', placeholder: 'Nome da Receita' %>
          <%= submit_tag 'Buscar' %>
        <% end %>
      </li>
      <li>
        <%= link_to 'Minhas Listas', lists_path %> 
      </li>
      <li>
        <% if user_signed_in? %>
          <%= link_to 'Sair', destroy_user_session_path, method: :delete %>
        <% else %>
          <%= link_to 'Entrar', new_user_session_path %>
        <% end %>
      </li>
      <li>
        <% if user_signed_in? %>
          <%= link_to 'Perfil',  '/profile' %>
        <% end %>
      </li>
    </ul>
  </div>
</nav>

app/views/users/profile.html.erb
<h1><%= current_user.email %></h1>
<%= render partial: 'recipes/recipe', collection: current_user.recipes %>